CREATE TABLE product
(
	ID 		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	NAME 	VARCHAR(255) NOT NULL,
	PRICE 	DECIMAL(10, 2) NOT NULL DEFAULT 0,
	ABOUT 	VARCHAR(255)
);

insert into product(NAME, PRICE, ABOUT) values('Laptop', 321, 'Jeftini laptop');
insert into product(NAME, PRICE, ABOUT) values('Mis', 311, 'Skupi mis');
insert into product(NAME, PRICE, ABOUT) values('Tipkovnica', 0.12, 'Tipkovnica koja ne radi');